version: 2

models:
  - name: stg_fact_orders
    description: "Staging model for cleaned orders data"
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
      - name: order_date
        tests:
          - not_null
      - name: amount
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              arguments:  # FIXED: Nest expression here
                expression: "{{ value }} > 0"
      - name: profit
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              arguments:  # FIXED: Nest expression here
                expression: "profit >= -amount * 2"