version: 2

models:
  - name: stg_fact_orders
    description: "Staging model for cleaned orders data"
    columns:
      - name: order_id
        description: "Unique order identifier"
        tests:
          - not_null
          - unique


      - name: customer_id
        description: "Customer ID"
        tests:
          - not_null

      - name: product_id
        description: "Product ID"
        tests:
          - not_null

      - name: quantity
        description: "Quantity of product ordered"
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              arguments:
                expression: "{{ value }} >= 0"

      - name: amount
        description: "Total order amount"
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              arguments:
                expression: "{{ value }} > 0"

      - name: profit
        description: "Order profit"
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              arguments:
                expression: "{{ value }} >= -amount * 2"

