ecommerce_dbt:
  # Default target can be overridden with env var DBT_DEFAULT_TARGET
  target: "{{ env_var('DBT_DEFAULT_TARGET', 'dev-local') }}"
  outputs:

    dev-local:    # Run dbt from your laptop
      type: postgres
      host: "{{ env_var('DB_HOST', 'localhost') }}"
      port: "{{ env_var('DB_PORT', '5432') }}"
      user: "{{ env_var('DB_USER', 'postgres') }}"
      password: "{{ env_var('DB_PASSWORD', 'postgres') }}"
      dbname: "{{ env_var('DB_NAME', 'ecommerce_dw') }}"
      schema: "{{ env_var('DB_SCHEMA', 'public') }}"
      threads: "{{ env_var('DB_THREADS', '1') }}"

    dev:          # Run dbt inside Airflow/Docker
      type: postgres
      host: "{{ env_var('DB_HOST', 'postgres') }}"
      port: "{{ env_var('DB_PORT', '5432') }}"
      user: "{{ env_var('DB_USER', 'airflow') }}"
      password: "{{ env_var('DB_PASSWORD', 'airflow') }}"
      dbname: "{{ env_var('DB_NAME', 'ecommerce_dw') }}"
      schema: "{{ env_var('DB_SCHEMA', 'public') }}"
      threads: "{{ env_var('DB_THREADS', '1') }}"
