ecommerce_dbt:
  target: dev     # Airflow should use this
  outputs:

    dev-local:    # Run dbt from your laptop
      type: postgres
      host: localhost
      port: 5433
      user: postgres
      password: "17970"
      dbname: ecommerce_dw
      schema: public
      threads: 1

    dev:          # Run dbt inside Airflow/Docker
      type: postgres
      host: postgres
      port: 5432
      user: airflow
      password: airflow
      dbname: ecommerce_dw
      schema: public
      threads: 1
